application: dgkeeper
version: 1
runtime: python
api_version: 1

handlers:
# - url: /dgkeeper.manifest
#   mime_type: text/cache-manifest
#   static_files: dgkeeper.manifest
#   upload: dgkeeper.manifest
  
- url: /images/(.*)
  static_files: static/images/\1
  upload: static/images/(.*)    

- url: /(.*.js)
  static_files: static/\1
  upload: static/.*.js
  expiration: 1d

- url: /scroller
  script: main.py  
  
- url: /static/(.*)
  static_files: static/\1
  upload: static/(.*)

- url: /.*
  script: main.py
  

